routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
/*--------------------------------ADMIN ROUTE------------------------------------------------------------------------*/
Route::group(['prefix' => 'admin','middleware' => ['auth','admin']],function (){
    Route::get('/',function (){
       return view('admin.dashboard');
    })->name('admin');
    Route::resource('student','StudentController')->except('show');
    Route::resource('teacher','TeacherController')->except('show');
    Route::resource('course','CourseController')->except('show');
    Route::resource('class','ClassController')->except('show');


});
/*--------------------------------END ADMIN ROUTE--------------------------------------------------------------------*/
/*--------------------------------STUDENT ROUTE----------------------------------------------------------------------*/

Route::group(['prefix' => 'student','middleware' => ['auth','student']],function (){
    Route::get('/','HomeController@student')->name('student');
});
/*--------------------------------END STUDENT ROUTE------------------------------------------------------------------*/
/*--------------------------------TEACHER ROUTE----------------------------------------------------------------------*/

Route::group(['prefix' => 'teacher','middleware' => ['auth','teacher']],function (){
    Route::get('/',function (){
        return view('home');
    })->name('teacher');
});
/*--------------------------------END TEACHER ROUTE------------------------------------------------------------------*/

resources/views/admin/class-form.blade.php
@extends('admin.layouts.admin')
@section('styles')
    <link rel="stylesheet" href="{{ asset('assets/admin/css/select2.css') }}">
@endsection
@section('scripts')
    <script src="{{ asset('assets/admin/js/select2.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#teacher_id').select2();
            $('#student_id').select2();
            $('#course_id').select2();
        });
    </script>
@endsection
@section('content')
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title"><strong><u>Class Add</u></strong></div>
                </div>
                <div class="ibox-body">
                    @if(isset($class_info))
                        {{ Form::open(['url' => route('class.update',$class_info->id),'class' => 'form','method' => 'patch']) }}
                        @else
                        {{ Form::open(['url' => route('class.store'),'class' => 'form']) }}
                        @endif
                    <div class="form-group row">
                        {{ Form::label('class','Class: ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::text('class',@$class_info->class,['class' => 'form-control'.($errors->has('class') ? 'is-invalid' : ''),'id' => 'class' ,'required' => true,'placeholder' => 'Enter Class']) }}
                            @error('class')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>

                            @enderror

                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('teacher_id','Teacher Name: ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::select('teacher_id[]',$teacher_name,@$class_info->teacher_id,['class' =>'form-control'.($errors->has('teacher_id') ? 'is-invalid': ''),'id' => 'teacher_id','required' => true, 'multiple'=>true]) }}
                            @error('teacher_id')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('student_id','Student Name ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::select('student_id[]',$student_name,@$class_info->student_id,['class' =>'form-control'.($errors->has('student_id') ? 'is-invalid': ''),'id' => 'student_id','required' => true, 'multiple'=>true]) }}
                            @error('student_id')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('course_id','Course Name ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::select('course_id[]',$course_name,@$class_info->course_id,['class' =>'form-control'.($errors->has('course_id') ? 'is-invalid': ''),'id' => 'course_id','required' => true, 'multiple'=>true]) }}
                            @error('course_id')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('status','Status: ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::select('status',['active' => 'Active','inactive' => 'Inactive'],@$class_infp->status,['class' =>'form-control'.($errors->has('status') ? 'is-invalid': ''),'id' => 'status','required' => true]) }}
                            @error('status')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('','',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::button('<i class="fa fa-trash"></i> Reset',['class' => 'btn btn-danger','type' =>'reset']) }}
                            {{ Form::button('<i class="fa fa-send"></i> Submit',['class' => 'btn btn-success','type' =>'submit']) }}
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/class.blade.php
@extends('admin.layouts.admin')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/css/dataTable.css') }}">
@endsection
@section('content')
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title"><strong><u>Class List</u></strong></div>
                    <div class="ibox-tools">
                        <a href="{{ route('class.create') }}"><button class="btn btn-outline-success"><i class="fa fa-plus"></i> Add class</button></a>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Class</th>
                            <th class="text-success">Teacher Name</th>
                            <th class="text-info">Course Name</th>
                            <th class="text-danger">Student Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($class_info as $key => $value)
{{--                            {{ dd($value) }}--}}
                            <tr>
                                <td class="text-info">{{ $key+1 }}</td>
                                <td>{{ $value->class }}</td>
                                <td class="font-weight-bold">
                                    @php
                                        $teacherList = $value->teacherInfo()->get()->map(function ($teacher){
                                            return $teacher->teacher_info->name;
                                        })->unique('id');

                                    @endphp
                                    @foreach($teacherList as $teacher)
                                        {{ ucfirst($teacher) }}
                                        @if(!$loop->last)
                                            ,
                                        @endif
                                    @endforeach


                                </td>
                                <td class="font-weight-bold">
                                    @php
                                        $course = $value->courseInfo()->get()->map(function ($course){
                                            return $course->course_info->CourseName;
                                        })->unique('id');
                                    @endphp

                                    @foreach($course as $courses)
                                        {{ ucfirst($courses) }}
                                        @if(!$loop->last)
                                            ,
                                        @endif
                                    @endforeach



                                </td>
                                <td class="font-weight-bold">
                                    @php
                                        $students = $value->studentInfo()->get()->map(function ($student){
                                            return $student->student_info->name;
                                        })->unique('id');

                                    @endphp


                                    @foreach($students as $student_info)
                                        {{ ucfirst($student_info) }}
                                        @if(!$loop->last)
                                            ,
                                        @endif
                                    @endforeach

                                </td>
                                <td>{{ ucfirst($value->status) }}</td>
                                <td>
                                    <a href="{{ route('class.edit',$value->id) }}" class="btn btn-success mb-2" style="border-radius: 50%"><i class="fa fa-pencil"></i></a>
                                    {{ Form::open(['url' => route('class.destroy',$value->id),'class' => 'form','method' => 'delete','onsubmit' =>'return confirm("Are You Sure Want to Delete")'])}}
                                    {{ Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius: 50%','type' => 'submit']) }}
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach














                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="{{ asset('assets/admin/js/dataTables.js') }}"></script>

    <script>
        $(document).ready( function () {
            $('.table').DataTable();
        } );
    </script>
@endsection

resources/views/admin/course-form.blade.php
@extends('admin.layouts.admin')
@section('styles')
    <link rel="stylesheet" href="{{ asset('assets/admin/css/select2.css') }}">
@endsection
@section('scripts')
    <script src="{{ asset('assets/admin/js/select2.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#teacher_id').select2();
            $('#student_id').select2();
        });
    </script>
@endsection
@section('content')
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title"><strong><u>Course Add</u></strong></div>
                </div>
                <div class="ibox-body">
                    @if(isset($course_id))

                        {{ Form::open(['url' => route('course.update',$course_id->id),'class' => 'form','method' => 'patch']) }}
                    @else
                        {{ Form::open(['url' => route('course.store'),'class' => 'form']) }}
                    @endif
                    <div class="form-group row">
                        {{ Form::label('CourseName','CourseName: ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::text('CourseName',@$course_id->CourseName,['class' => 'form-control'.($errors->has('CourseName') ? 'is-invalid' : ''),'id' => 'CourseName' ,'required' => true,'placeholder' => 'Enter Course Name Name']) }}
                            @error('CourseName')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>

                            @enderror
                        </div>
                    </div>



                    <div class="form-group row">
                        {{ Form::label('teacher_id','Teacher Name: ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::select('teacher_id[]',$teacher_name,@$course_id->teacher_id,['class' =>'form-control'.($errors->has('teacher_id') ? 'is-invalid': ''),'id' => 'teacher_id','required' => true, 'multiple'=>true]) }}
                            @error('teacher_id')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('student_id','Student Name ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::select('student_id[]',$student_name,@$course_id->student_id,['class' =>'form-control'.($errors->has('student_id') ? 'is-invalid': ''),'id' => 'student_id','required' => true, 'multiple'=>true]) }}
                            @error('student_id')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('description','Description: ',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::textarea('description',@$course_id->description,['class' => 'form-control'.($errors->has('description') ? 'is-invalid' : ''),'id' => 'description' ,'rows' => 5, 'cols' => 5,'style' => 'resize:none','required' => true]) }}

                            @error('description')
                            <p class="invalid-feedback">
                                {{ $message }}
                            </p>

                            @enderror
                        </div>
                    </div>





                    <div class="form-group row">
                        {{ Form::label('','',['class' => 'col-sm-3'] )}}
                        <div class="col-sm-9">
                            {{ Form::button('<i class="fa fa-trash"></i> Reset',['class' => 'btn btn-danger','type' =>'reset']) }}
                            {{ Form::button('<i class="fa fa-send"></i> Submit',['class' => 'btn btn-success','type' =>'submit']) }}
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/course.blade.php
@extends('admin.layouts.admin')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/css/dataTable.css') }}">
@endsection
@section('content')
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title"><strong><u>Course List</u></strong></div>
                    <div class="ibox-tools">
                        <a href="{{ route('course.create') }}"><button class="btn btn-outline-success"><i class="fa fa-plus"></i> Add Course</button></a>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Course Name</th>
                             <th>Teacher Name</th>
                             <th>Student Name</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                                @foreach($teacher_name as $key => $value)
                                     <tr>
                                         <td>{{ $key+1 }}</td>
                                         <td>{{ $value->CourseName }}</td>
                                         <td>
                                             @php
                                                 $teacherList = $value
                                                 ->teacherInfo
                                                 ->pluck('teacher_id')
                                                 ->unique()
                                                 ->map(function($query){
                                                    return \App\Models\Teacher::find($query)->name;
                                                 });
                                             @endphp

                                                 @foreach($teacherList as $teacher)
                                                     {{ $teacher}}
                                                     @if(!$loop->last)
                                                         ,
                                                     @endif
                                                 @endforeach



                                         </td>
                                         <td>
                                            @php
                                                 $studentList = $value
                                                    ->studentInfo
                                                    ->pluck('student_id')
                                                    ->unique()
                                                    ->map(function($query){
                                                    return \App\Models\Student::find($query)->name;
                                                    });
                                             @endphp
                                                 @foreach($studentList as $student_data)
                                                     {{ $student_data}}
                                                     @if(!$loop->last)
                                                         ,
                                                     @endif
                                                     @endforeach
                                         </td>
                                         <td>{{ $value->description }}</td>
                                         <td>
                                             <a href="{{ route('course.edit',$value->id) }}" class="btn btn-success mb-2" style="border-radius: 50%"><i class="fa fa-pencil"></i></a>
                                             {{ Form::open(['url' => route('course.destroy',$value->id),'class' => 'form','method' => 'delete','onsubmit' =>'return confirm("Are You Sure Want to Delete")'])}}
                                             {{ Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius: 50%','type' => 'submit']) }}
                                             {{ Form::close() }}
                                         </td>
                                     </tr>
                                    @endforeach





                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="{{ asset('assets/admin/js/dataTables.js') }}"></script>

    <script>
        $(document).ready( function () {
            $('.table').DataTable();
        } );
    </script>
@endsection

resources/views/admin/student.blade.php
@extends('admin.layouts.admin')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/css/dataTable.css') }}">
@endsection
@section('content')
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title"><strong><u>Student List</u></strong></div>
                    <div class="ibox-tools">
                        <a href="{{ route('student.create') }}"><button class="btn btn-outline-success"><i class="fa fa-plus"></i> Add Student</button></a>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Name</th>
                            <th>Thumbnail</th>
                            <th>Address</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($student_data)
                            @foreach($student_data as $key => $value)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ ucfirst($value->name) }}</td>
                                    <td>
                                         @if($value->image != null && file_exists(public_path().'/uploads/student/Thumb-'.$value->image))
                                            <img src="{{ asset('uploads/student/Thumb-'.$value->image) }}" alt="image" class="img img-fluid img-thumbnail" style="max-width:150px">
                                        @endif
                                    </td>
                                    <td>
                                        {{ $value->address }}
                                    </td>
                                    <td>{{ $value->email }}</td>
                                    <td>{{ $value->number }}</td>
                                    <td>{{ ucfirst($value->status) }}</td>
                                    <td>
                                        <a href="{{ route('student.edit',$value->id) }}" class="btn btn-success mb-2" style="border-radius: 50%"><i class="fa fa-pencil"></i></a>
                                        {{ Form::open(['url' => route('student.destroy',$value->id),'class' => 'form','method' => 'delete','onsubmit' =>'return confirm("Are You Sure Want to Delete")']) }}
                                        {{ Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius: 50%','type' => 'submit']) }}
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                                @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="{{ asset('assets/admin/js/dataTables.js') }}"></script>

    <script>
        $(document).ready( function () {
            $('.table').DataTable();
        } );
    </script>
@endsection

resources/views/admin/teacher.blade.php
@extends('admin.layouts.admin')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/css/dataTable.css') }}">
@endsection
@section('content')
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title"><strong><u>Teacher List</u></strong></div>
                    <div class="ibox-tools">
                        <a href="{{ route('teacher.create') }}"><button class="btn btn-outline-success"><i class="fa fa-plus"></i> Add Teacher</button></a>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Teacher_Name</th>
                            <th>Student_Name</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th>status</th>
                            <th>Thumbnail</th>
                            <th>Address</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($teacher_data)
                            @foreach($teacher_data as $key => $value)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $value->name }}</td>
                                    <td>
                                        @if($value->student_info)
                                            @foreach($value->student_info as $student_data)
                                                {{ $student_data->students_info->name }}
                                                @if(!$loop->last)
                                                    ,
                                                @endif
                                            @endforeach
                                        @endif
                                    </td>
                                    <td>{{ $value->email }}</td>
                                    <td>{{ $value->number }}</td>
                                    <td>{{ ucfirst($value->status) }}</td>
                                    <td>
                                        @if($value->image != null && file_exists(public_path().'/uploads/teacher/Thumb-'.$value->image))
                                            <img src="{{ asset('uploads/teacher/Thumb-'.$value->image) }}" alt="image" class="img img-fluid img-thumbnail" style="max-width:150px">
                                        @endif
                                    </td>
                                    <td>
                                        {{ $value->address }}
                                    </td>
                                    <td>
                                        <a href="{{ route('teacher.edit',$value->id) }}" class="btn btn-success mb-2" style="border-radius: 50%"><i class="fa fa-pencil"></i></a>
                                        {{ Form::open(['url' => route('teacher.destroy',$value->id),'class' => 'form','method' => 'delete'])}}
                                        {{ Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius: 50%','type' => 'submit']) }}
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="{{ asset('assets/admin/js/dataTables.js') }}"></script>

    <script>
        $(document).ready( function () {
            $('.table').DataTable();
        } );
    </script>
@endsection