routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
/*--------------------------------ADMIN ROUTE------------------------------------------------------------------------*/
Route::group(['prefix' => 'admin','middleware' => ['auth','admin']],function (){
    Route::get('/',function (){
       return view('admin.dashboard');
    })->name('admin');
    Route::resource('student','StudentController')->except('show');
    Route::resource('teacher','TeacherController')->except('show');
    Route::resource('course','CourseController')->except('show');
    Route::resource('class','ClassController')->except('show');


});
/*--------------------------------END ADMIN ROUTE--------------------------------------------------------------------*/
/*--------------------------------STUDENT ROUTE----------------------------------------------------------------------*/

Route::group(['prefix' => 'student','middleware' => ['auth','student']],function (){
    Route::get('/','HomeController@student')->name('student');
});
/*--------------------------------END STUDENT ROUTE------------------------------------------------------------------*/
/*--------------------------------TEACHER ROUTE----------------------------------------------------------------------*/

Route::group(['prefix' => 'teacher','middleware' => ['auth','teacher']],function (){
    Route::get('/',function (){
        return view('home');
    })->name('teacher');
});
/*--------------------------------END TEACHER ROUTE------------------------------------------------------------------*/

resources/views/admin/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title>{{ config('app.name') }}</title>
    <meta name="csrf_token" content="{{ csrf_token() }}">
    <!-- GLOBAL MAINLY STYLES-->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="{{ asset('assets/admin/vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" />

    <link href="{{ asset('assets/admin/vendor/themify-icons/css/themify-icons.css') }}" rel="stylesheet" />
    <!-- PLUGINS STYLES-->
    <link href="{{ asset('assets/admin/vendor/jvectormap/jquery-jvectormap-2.0.3.css') }}" rel="stylesheet" />
    <!-- THEME STYLES-->
    <link href="{{ asset('assets/admin/css/main.min.css') }}" rel="stylesheet" />
    <!-- PAGE LEVEL STYLES-->
    @yield('styles')
</head>

<body class="fixed-navbar">
<div class="page-wrapper">

    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')

    <div class="content-wrapper">
    @include('admin.layouts.notification')
    @yield('content')
        <footer class="page-footer">
            <div class="font-13">{{ date('Y') }} © <b>Admin</b> - All rights reserved.</div>
            <a class="px-4" href="http://themeforest.net/item/adminca-responsive-bootstrap-4-3-angular-4-admin-dashboard-template/20912589" target="_blank">Admin</a>
            <div class="to-top"><i class="fa fa-angle-double-up"></i></div>
        </footer>
    </div>
</div>

<!-- BEGIN PAGA BACKDROPS-->
<div class="sidenav-backdrop backdrop"></div>
<div class="preloader-backdrop">
    <div class="page-preloader">Loading</div>
</div>
<!-- END PAGA BACKDROPS-->
<!-- CORE PLUGINS-->
<script src="{{ asset('assets/admin/vendor/jquery/dist/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/admin/vendor/popper.js/dist/umd/popper.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/admin/vendor/bootstrap/dist/js/bootstrap.min.js') }}" type="text/javascript"></script>

<script src="{{ asset('assets/admin/vendor/metisMenu/dist/metisMenu.min.js') }}" type="text/javascript"></script>

<script src="{{ asset('assets/admin/vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}" type="text/javascript"></script>

<!-- CORE SCRIPTS-->
<script src="{{ asset('assets/admin/js/app.min.js') }}" type="text/javascript"></script>

@yield('scripts')
<script>
    setTimeout(function () {
        $('.alert').slideUp();
    },2000);
</script>
</body>
</html>

resources/views/admin/layouts/header.blade.php
<!-- START HEADER-->
<header class="header">
    <div class="page-brand">
        <a class="link" href="index.html">
            <span class="text-center">School Dashboard</span>
        </a>
    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>

        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    <img src="{{ asset('assets/admin/img/admin.png') }}" />
                    <span></span>{{ request()->user()->name }}<i class="fa fa-angle-down m-l-5"></i></a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="fa fa-power-off"></i> Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </ul>
            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>
<!-- END HEADER-->

resources/views/admin/layouts/notification.blade.php
@if(session('success'))
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ session('success') }}
    </div>
@endif
@if(session('error'))
    <div class="alert alert-error alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ session('error') }}
    </div>
@endif
@if(session('warning'))
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ session('warning') }}
    </div>
@endif
@if(session('status'))
    <div class="alert alert-status alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ session('status') }}
    </div>
@endif

resources/views/admin/layouts/sidebar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                <img src="{{ asset('assets/admin/img/admin.png') }}" width="45px"  style="background-color: white;"/>
            </div>
            <div class="admin-info">
                <div class="font-strong">{{ request()->user()->name }}</div><small>{{ request()->user()->name }}</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{ route('admin') }}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{{route('student.index') }}"><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">Student Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('teacher.index') }}"><i class="sidebar-item-icon fa fa-map-marker"></i>
                    <span class="nav-label">Teacher Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('course.index') }}"><i class="sidebar-item-icon fa fa-sitemap"></i>
                    <span class="nav-label">Course Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('class.index') }}"><i class="sidebar-item-icon fa fa-universal-access"></i>
                    <span class="nav-label">Class Management</span>
                </a>
            </li>
            <li>
                <a href="icons.html"><i class="sidebar-item-icon fa fa-fast-forward"></i>
                    <span class="nav-label">Attendance Management</span>
                </a>
            </li>


        </ul>
    </div>
</nav>
<!-- END SIDEBAR-->